apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: my-web-app
    name: my-web-app-deployment
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: my-web-app
    template:
      metadata:
        labels:
          app: my-web-app
      spec:
        containers:
        - image: public.ecr.aws/r4q1n2d3/my-web-app:v1
          imagePullPolicy: Always
          name: frontend
          ports:
          - containerPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    name: my-web-app
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: my-web-app
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: my-web-app-ingress
  spec:
    rules:
    - host: my-web-app.irlhc08-cf7808d3396a7c1915bd1818afbfb3c0-0000.us-south.containers.appdomain.cloud
      http:
        paths:
        - backend:
            service:
              name: my-web-app
              port:
                number: 8080
          path: /
          pathType: Prefix
kind: List
metadata: {}
